# Generated by Django 6.0.5 on 2026-05-19 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.EmailField(help_text='Endereço de e-mail corporativo', max_length=254, unique=True)),
                ('employee_name', models.CharField(help_text='Nome do funcionário vinculado', max_length=150)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('BLOCKED', 'Bloqueada')], default='ACTIVE', max_length=20)),
                ('last_password_reset', models.DateTimeField(blank=True, help_text='Data do último reset de senha', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender', models.EmailField(help_text='Remetente', max_length=254)),
                ('recipient', models.EmailField(help_text='Destinatário', max_length=254)),
                ('subject', models.CharField(help_text='Assunto da Mensagem', max_length=255)),
                ('status', models.CharField(choices=[('DELIVERED', 'Entregue'), ('FAILED', 'Falhou'), ('SPAM', 'Retido (Spam)')], max_length=20)),
                ('error_message', models.TextField(blank=True, help_text='Código/Mensagem de erro técnico (ex: 550)', null=True)),
                ('timestamp', models.DateTimeField(help_text='Data/Hora Exata do Envio')),
            ],
        ),
    ]
