# Generated by Django 6.0.5 on 2026-05-19 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailDomain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: empresa.com.br', max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='MailLog',
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='username',
            field=models.CharField(help_text='Prefixo (ex: joao.silva)', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='last_password_reset',
            field=models.DateTimeField(blank=True, help_text='Data do último reset', null=True),
        ),
        migrations.AddField(
            model_name='emailaccount',
            name='domain',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accounts', to='emails.emaildomain'),
        ),
        migrations.AlterUniqueTogether(
            name='emailaccount',
            unique_together={('username', 'domain')},
        ),
        migrations.RemoveField(
            model_name='emailaccount',
            name='address',
        ),
    ]
