# Generated by Django 6.0.7 on 2026-07-20 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0002_emaildomain_delete_maillog_emailaccount_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailaccount',
            name='password',
            field=models.CharField(blank=True, max_length=255, verbose_name='Senha'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='employee_name',
            field=models.CharField(help_text='Nome do funcionário vinculado', max_length=150, verbose_name='Vínculo'),
        ),
        migrations.AlterField(
            model_name='emailaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('BLOCKED', 'Bloqueada')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
