# Generated by Django 6.0.7 on 2026-07-20 16:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0003_emailaccount_password_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailaccount',
            name='last_password_reset',
        ),
    ]
