# Generated by Django 6.0.5 on 2026-05-19 00:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Título ou resumo do problema.', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Descrição detalhada do chamado.')),
                ('status', models.CharField(choices=[('NEW', 'Novos'), ('IN_PROGRESS', 'Em Atendimento'), ('PENDING', 'Pendente'), ('RESOLVED', 'Resolvido')], default='NEW', help_text='Coluna atual do cartão no Kanban.', max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Baixa'), ('MEDIUM', 'Média'), ('HIGH', 'Alta'), ('URGENT', 'Urgente')], default='MEDIUM', help_text='Nível de prioridade do chamado.', max_length=20)),
                ('category', models.CharField(choices=[('HARDWARE', 'Hardware'), ('SOFTWARE', 'Software'), ('NETWORK', 'Rede'), ('OTHER', 'Outros')], default='OTHER', help_text='Categoria do problema.', max_length=20)),
                ('requester_name', models.CharField(help_text='Nome do solicitante (ex: vindo do WhatsApp).', max_length=150)),
                ('is_active', models.BooleanField(default=True, help_text='Indica se o registro está ativo (Soft delete).')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='Data e hora de criação.')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='Data e hora da última atualização.')),
                ('assigned_to', models.ForeignKey(blank=True, help_text='Técnico responsável pelo chamado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Texto do comentário ou atualização do histórico.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(help_text='Usuário que fez o comentário (ou None se for do sistema).', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('ticket', models.ForeignKey(help_text='Chamado ao qual o comentário pertence.', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='helpdesk.ticket')),
            ],
        ),
    ]
