# Generated by Django 6.0.5 on 2026-05-19 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_archived',
            field=models.BooleanField(default=False, help_text='Indica se o chamado foi arquivado após um tempo resolvido.'),
        ),
    ]
