# Generated by Django 6.0.5 on 2026-06-15 12:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0007_ticket_description_required'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSpecificCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome exibido da categoria específica.', max_length=80, unique=True)),
                ('is_active', models.BooleanField(default=True, help_text='Categorias inativas não aparecem no formulário.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'categoria específica',
                'verbose_name_plural': 'categorias específicas',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ticket',
            name='specific_category',
            field=models.ForeignKey(blank=True, help_text='Categoria específica definida pela TI.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='helpdesk.ticketspecificcategory'),
        ),
    ]
