# Generated by Django 6.0.5 on 2026-06-15 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0008_ticketspecificcategory_ticket_specific_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='is_rejected',
            field=models.BooleanField(default=False, help_text='Indica se o chamado foi recusado pelo técnico.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='rejection_reason',
            field=models.TextField(blank=True, help_text='Motivo da recusa do chamado.', null=True),
        ),
    ]
