# Generated by Django 6.0.5 on 2026-06-15 13:33

import django.db.models.deletion
import helpdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0009_ticket_is_rejected_ticket_rejection_reason'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(help_text='Nome original do arquivo.', max_length=255)),
                ('file', models.FileField(upload_to=helpdesk.models.attachment_upload_path, validators=[helpdesk.models.validate_image_attachment])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='helpdesk.ticket')),
            ],
        ),
    ]
