# Generated by Django 6.0.5 on 2026-06-15 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0010_ticketattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unread_by_tech',
            field=models.BooleanField(default=False, help_text='Possui interações não lidas pela TI.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unread_by_user',
            field=models.BooleanField(default=False, help_text='Possui interações não lidas pelo usuário.'),
        ),
    ]
