# Generated by Django 6.0.5 on 2026-06-15 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_equipe_customuser_equipes'),
        ('helpdesk', '0011_ticket_unread_by_tech_ticket_unread_by_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='equipe',
            field=models.ForeignKey(blank=True, help_text='Equipe/Setor de contexto para este chamado.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='core.equipe'),
        ),
    ]
