# Generated by Django 6.0.5 on 2026-06-16 15:39

import helpdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0012_ticket_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Imagem anexada ao comentário.', null=True, upload_to=helpdesk.models.attachment_upload_path, validators=[helpdesk.models.validate_image_attachment]),
        ),
    ]
