# Generated by Django 6.0.5 on 2026-06-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0013_comment_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='unread_count_tech',
            field=models.IntegerField(default=0, help_text='Quantidade de interações não lidas pela TI.'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='unread_count_user',
            field=models.IntegerField(default=0, help_text='Quantidade de interações não lidas pelo usuário.'),
        ),
    ]
