# Generated by Django 5.2.5 on 2026-07-06 15:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0019_pushsubscription'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketUnread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unreads', to='helpdesk.ticket')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unread_tickets_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'notificação não lida',
                'verbose_name_plural': 'notificações não lidas',
                'unique_together': {('ticket', 'user')},
            },
        ),
    ]
