# Generated by Django 5.2.5 on 2026-07-06 15:58

import helpdesk.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0020_ticketunread'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='attachment',
            field=models.FileField(blank=True, help_text='Arquivo anexado ao comentário.', null=True, upload_to=helpdesk.models.attachment_upload_path, validators=[helpdesk.models.validate_file_attachment]),
        ),
    ]
