# Generated by Django 6.0.6 on 2026-07-30 16:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('helpdesk', '0025_ticket_assistente_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InformativeMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(help_text='Conteúdo da mensagem.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('acknowledged_by', models.ManyToManyField(blank=True, help_text='Usuários que deram OK na mensagem.', related_name='acknowledged_info_msgs', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(help_text='Usuário que enviou a mensagem.', on_delete=django.db.models.deletion.PROTECT, related_name='informative_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'mensagem informativa',
                'verbose_name_plural': 'mensagens informativas',
                'ordering': ['created_at'],
            },
        ),
    ]
