# Generated by Django 6.0.5 on 2026-06-10 17:03

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_registroacao_index_names'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
                ('objects', core.models.CustomUserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('IT_USER', 'Usuário TI'), ('STANDARD', 'Usuário Padrão')], default='STANDARD', help_text='Papel do usuário no sistema (define permissões de acesso).', max_length=20),
        ),
    ]
