# Generated by Django 6.0.5 on 2026-06-15 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_customuser_managers_alter_customuser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrador'), ('IT_USER', 'Usuário TI'), ('SUPERVISOR', 'Supervisor'), ('STANDARD', 'Usuário Padrão')], default='STANDARD', help_text='Papel do usuário no sistema (define permissões de acesso).', max_length=20),
        ),
    ]
