# Generated by Django 6.0.5 on 2026-06-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='equipe',
        ),
        migrations.AddField(
            model_name='customuser',
            name='equipes',
            field=models.ManyToManyField(blank=True, help_text='Equipes do usuário (opcional; atribuída pelo administrador).', related_name='membros', to='core.equipe'),
        ),
    ]
