# Generated by Django 5.2.5 on 2026-06-22 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_customuser_equipe_customuser_equipes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='registroacao',
            name='acao',
            field=models.CharField(choices=[('CREATED', 'Criação'), ('UPDATED', 'Atualização'), ('STATUS_CHANGED', 'Mudança de status'), ('ASSIGNED', 'Atribuição'), ('TRANSFERRED', 'Transferência'), ('RETURNED', 'Devolução'), ('DELIVERY', 'Entrega'), ('COMMENT', 'Comentário'), ('ACTIVATED', 'Ativação'), ('DEACTIVATED', 'Desativação'), ('PASSWORD_RESET', 'Reset de senha'), ('RECHARGE', 'Recarga'), ('BLOCKED', 'Bloqueio'), ('UNBLOCKED', 'Desbloqueio'), ('DELETED', 'Exclusão')], db_index=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='registroacao',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
