# Generated by Django 6.0.5 on 2026-07-24 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_customuser_id_alter_equipe_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacao',
            name='modulo',
            field=models.CharField(choices=[('helpdesk', 'Helpdesk'), ('chips', 'Chips'), ('emails', 'E-mails'), ('equipment', 'Equipamentos'), ('discador', 'Discadores'), ('core', 'Core')], db_index=True, max_length=20),
        ),
    ]
