# Generated by Django 6.0.6 on 2026-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_registroacao_modulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registroacao',
            name='modulo',
            field=models.CharField(choices=[('helpdesk', 'Helpdesk'), ('chips', 'Chips'), ('emails', 'E-mails'), ('equipment', 'Equipamentos'), ('discador', 'Discadores'), ('operadores', 'Operadores'), ('core', 'Core')], db_index=True, max_length=20),
        ),
    ]
