# Generated by Django 6.0.5 on 2026-05-19 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NOTEBOOK', 'Notebook'), ('DESKTOP', 'Desktop'), ('MONITOR', 'Monitor'), ('SMARTPHONE', 'Smartphone'), ('PERIPHERAL', 'Periférico'), ('OTHER', 'Outro')], default='NOTEBOOK', max_length=20)),
                ('tag', models.CharField(help_text='Código de Patrimônio (Tag)', max_length=100, unique=True)),
                ('serial_number', models.CharField(help_text='Número de Série', max_length=150, unique=True)),
                ('brand_model', models.CharField(help_text='Marca / Modelo', max_length=200)),
                ('purchase_date', models.DateField(help_text='Data de Compra')),
                ('warranty_end', models.DateField(help_text='Data Fim da Garantia')),
                ('purchase_value', models.DecimalField(decimal_places=2, help_text='Valor de Compra', max_digits=10)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('IN_USE', 'Em Uso'), ('MAINTENANCE', 'Em Manutenção'), ('SCRAP', 'Sucata/Descartado')], default='AVAILABLE', max_length=20)),
                ('current_employee', models.CharField(blank=True, help_text='Funcionário Atual', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='EquipmentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('ASSIGNED', 'Atribuição'), ('RETURNED', 'Devolução'), ('MAINTENANCE', 'Enviado para Manutenção'), ('SCRAPPED', 'Descartado/Sucateado'), ('CREATED', 'Cadastro Inicial')], max_length=20)),
                ('employee_name', models.CharField(blank=True, help_text='Funcionário Envolvido', max_length=200, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='equipment.equipment')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
