# Generated by Django 6.0.5 on 2026-05-19 14:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(help_text='Identificador do Lote/Saquinho', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado')], default='OPEN', max_length=20)),
                ('received_at', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Nome da operadora (Ex: Claro, Vivo)', max_length=100, unique=True)),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa')], default='ACTIVE', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Chip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_number', models.CharField(help_text='Número da Linha com DDD', max_length=20, unique=True)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Disponível'), ('IN_USE', 'Em Uso'), ('BLOCKED', 'Bloqueado'), ('CANCELED', 'Cancelado'), ('LOST', 'Perdido')], default='AVAILABLE', max_length=20)),
                ('technology', models.CharField(choices=[('PHYSICAL', 'Físico'), ('ESIM', 'eSIM')], default='PHYSICAL', max_length=20)),
                ('fixed_cost', models.DecimalField(decimal_places=2, default=0.0, help_text='Custo Fixo do Plano', max_digits=10)),
                ('iccid', models.CharField(blank=True, help_text='ICCID (Número de série do chip)', max_length=50, null=True, unique=True)),
                ('plan_type', models.CharField(choices=[('PREPAID', 'Pré-pago'), ('POSTPAID', 'Pós-pago'), ('CONTROL', 'Controle')], default='CONTROL', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chips', to='chips.batch')),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chips', to='chips.operator')),
            ],
        ),
        migrations.CreateModel(
            name='ChipMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_name', models.CharField(help_text='Nome do funcionário que recebeu/devolveu', max_length=150)),
                ('action', models.CharField(choices=[('DELIVERY', 'Entrega'), ('RETURN', 'Devolução')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movements', to='chips.chip')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='chips.chip')),
                ('registered_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
