# Generated by Django 6.0.5 on 2026-06-10 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0002_chip_custody_batch_envelope'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='identifier',
            field=models.CharField(help_text='Identificador do Lote/Saquinho', max_length=100, unique=True, verbose_name='Identificador'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='nome',
            field=models.CharField(blank=True, help_text='Nome escrito no envelope.', max_length=150, verbose_name='Nome no Envelope'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='setor',
            field=models.CharField(blank=True, help_text='Setor escrito no envelope.', max_length=100, verbose_name='Setor'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('OPEN', 'Aberto'), ('CLOSED', 'Fechado')], default='OPEN', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='tipo',
            field=models.CharField(choices=[('LOTE', 'Lote'), ('ENVELOPE', 'Envelope')], default='ENVELOPE', help_text='Lote de recebimento ou envelope físico na TI.', max_length=20, verbose_name='Tipo'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='activated_at',
            field=models.DateField(blank=True, help_text='Data de ativação no callcenter (primeira entrega).', null=True, verbose_name='Data de Ativação'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='batch',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chips', to='chips.batch', verbose_name='Envelope'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='custody',
            field=models.CharField(choices=[('WITH_TI', 'Na TI'), ('WITH_PERSON', 'Com pessoa')], default='WITH_TI', help_text='Onde o chip está fisicamente agora.', max_length=20, verbose_name='Custódia'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='fixed_cost',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Custo Fixo do Plano', max_digits=10, verbose_name='Custo Fixo'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='iccid',
            field=models.CharField(blank=True, help_text='ICCID (Número de série do chip)', max_length=50, null=True, unique=True, verbose_name='ICCID'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='line_number',
            field=models.CharField(help_text='Número da Linha com DDD', max_length=20, unique=True, verbose_name='Número da Linha'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='chips', to='chips.operator', verbose_name='Operadora'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='plan_type',
            field=models.CharField(choices=[('PREPAID', 'Pré-pago'), ('POSTPAID', 'Pós-pago'), ('CONTROL', 'Controle')], default='CONTROL', max_length=20, verbose_name='Tipo de Plano'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível'), ('IN_USE', 'Em Uso'), ('BLOCKED', 'Bloqueado'), ('CANCELED', 'Cancelado'), ('LOST', 'Perdido')], default='AVAILABLE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='technology',
            field=models.CharField(choices=[('PHYSICAL', 'Físico'), ('ESIM', 'eSIM')], default='PHYSICAL', max_length=20, verbose_name='Tecnologia'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='name',
            field=models.CharField(help_text='Nome da operadora (Ex: Claro, Vivo)', max_length=100, unique=True, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('INACTIVE', 'Inativa')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='chip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recharges', to='chips.chip', verbose_name='Chip'),
        ),
    ]
