# Generated by Django 6.0.5 on 2026-06-10 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0003_alter_batch_identifier_alter_batch_nome_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='setor',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='tipo',
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('INACTIVE', 'Inativo')], default='ACTIVE', max_length=20, verbose_name='Status'),
        ),
    ]
