# Generated by Django 6.0.5 on 2026-06-10 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0004_remove_batch_setor_remove_batch_tipo_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='identifier',
        ),
    ]
