# Generated by Django 6.0.5 on 2026-06-10 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0005_remove_batch_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='status',
        ),
    ]
