# Generated by Django 5.2.5 on 2026-06-12 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0006_remove_batch_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='custody',
        ),
        migrations.RemoveField(
            model_name='chip',
            name='fixed_cost',
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível na TI'), ('IN_USE', 'Em Uso'), ('BLOCKED', 'Bloqueado'), ('CANCELED', 'Cancelado'), ('LOST', 'Perdido')], default='AVAILABLE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chipmovement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
