# Generated by Django 6.0.5 on 2026-06-13 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0007_remove_chip_custody_remove_chip_fixed_cost_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível'), ('IN_USE', 'Em Uso'), ('BLOCKED', 'Bloqueado'), ('CANCELED', 'Cancelado'), ('LOST', 'Perdido')], default='AVAILABLE', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='chipmovement',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
