# Generated by Django 5.2.5 on 2026-06-22 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0008_alter_batch_id_alter_chip_id_alter_chip_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='email_vinculado',
            field=models.BooleanField(default=False, help_text='Indica se a linha tem algum e-mail vinculado', verbose_name='E-mail Vinculado'),
        ),
        migrations.AddField(
            model_name='chip',
            name='observacao',
            field=models.TextField(blank=True, help_text='Observações sobre o chip', verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chip',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='chipmovement',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='operator',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='recharge',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
