# Generated by Django 6.0.7 on 2026-07-17 15:40

from django.db import migrations, models

def migrate_chip_status(apps, schema_editor):
    Chip = apps.get_model('chips', 'Chip')
    for chip in Chip.objects.all():
        if chip.status == 'AVAILABLE':
            chip.status = 'ACTIVE'
            chip.usage_status = 'AVAILABLE'
        elif chip.status == 'IN_USE':
            chip.status = 'ACTIVE'
            chip.usage_status = 'IN_USE'
        else:
            chip.usage_status = 'UNAVAILABLE'
            # the physical status for others remains the same ('BLOCKED', 'CANCELED', 'LOST', etc)
        chip.save()

def reverse_migrate_chip_status(apps, schema_editor):
    pass

class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0010_alter_batch_id_alter_chip_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='usage_status',
            field=models.CharField(choices=[('AVAILABLE', 'Disponível'), ('IN_USE', 'Em Uso'), ('UNAVAILABLE', 'Indisponível')], default='AVAILABLE', max_length=20, verbose_name='Status de Uso'),
        ),
        migrations.RunPython(migrate_chip_status, reverse_migrate_chip_status),
        migrations.AlterField(
            model_name='chip',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('BLOCKED', 'Bloqueado'), ('CANCELED', 'Cancelado'), ('LOST', 'Perdido'), ('OTHER', 'Outro')], default='ACTIVE', max_length=20, verbose_name='Status do Chip'),
        ),
    ]
