# Generated by Django 6.0.7 on 2026-07-21 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0011_chip_usage_status_alter_chip_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chip',
            name='email_vinculado',
        ),
    ]
