# Generated by Django 6.0.7 on 2026-07-21 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0012_remove_chip_email_vinculado'),
        ('emails', '0004_remove_emailaccount_last_password_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='chip',
            name='email_vinculado',
            field=models.ForeignKey(blank=True, help_text='Conta de e-mail vinculada a este chip', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chips', to='emails.emailaccount', verbose_name='E-mail Vinculado'),
        ),
    ]
