# Generated by Django 6.0.7 on 2026-07-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0013_chip_email_vinculado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chip',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativo'), ('BANNED', 'Banido'), ('CANCELED', 'Cancelado'), ('LOST', 'Perdido'), ('OTHER', 'Outro')], default='ACTIVE', max_length=20, verbose_name='Status do Chip'),
        ),
    ]
