# Generated by Django 6.0.7 on 2026-07-28 18:03

from django.db import migrations


def forwards_func(apps, schema_editor):
    Chip = apps.get_model('chips', 'Chip')
    Chip.objects.filter(status='BLOCKED').update(status='BANNED')

def reverse_func(apps, schema_editor):
    Chip = apps.get_model('chips', 'Chip')
    Chip.objects.filter(status='BANNED').update(status='BLOCKED')

class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0014_alter_chip_status'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
