# Generated by Django 6.0.6 on 2026-07-30 15:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chips', '0015_update_blocked_to_banned'),
        ('operadores', '0006_alter_whatsappaccount_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chipmovement',
            name='employee_operador',
            field=models.ForeignKey(blank=True, help_text='Operador do módulo de callcenter vinculado ao titular.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chip_movements', to='operadores.operador'),
        ),
    ]
