# Generated by Django 6.0.5 on 2026-07-24 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chips', '0013_chip_email_vinculado'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ilha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome da Ilha')),
            ],
            options={
                'verbose_name': 'Ilha',
                'verbose_name_plural': 'Ilhas',
                'ordering': ['setor__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: INSS, LOJA, SIAPE', max_length=100, unique=True, verbose_name='Nome do Setor')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Ex: PA 01', max_length=100, verbose_name='Nome da PA')),
                ('ilha', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pas', to='operadores.ilha', verbose_name='Ilha')),
            ],
            options={
                'verbose_name': 'PA',
                'verbose_name_plural': 'PAs',
                'ordering': ['ilha__name', 'name'],
                'unique_together': {('name', 'ilha')},
            },
        ),
        migrations.CreateModel(
            name='Operador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nome do Operador')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('pa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operadores', to='operadores.pa', verbose_name='Posição de Atendimento (PA)')),
            ],
            options={
                'verbose_name': 'Operador',
                'verbose_name_plural': 'Operadores',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='ilha',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilhas', to='operadores.setor', verbose_name='Setor'),
        ),
        migrations.CreateModel(
            name='WhatsAppAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(help_text='Número do WhatsApp', max_length=50, unique=True, verbose_name='Número / Identificador')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('RESTRICTED', 'Restringida'), ('SUSPENDED', 'Suspendida'), ('BANNED', 'Banida')], default='ACTIVE', max_length=20, verbose_name='Status da Conta')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chip', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_account', to='chips.chip', verbose_name='Chip Vinculado')),
                ('operador', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_accounts', to='operadores.operador', verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Conta WhatsApp',
                'verbose_name_plural': 'Contas WhatsApp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterUniqueTogether(
            name='ilha',
            unique_together={('name', 'setor')},
        ),
    ]
