# Generated by Django 6.0.5 on 2026-07-24 18:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_registroacao_modulo'),
        ('operadores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ilha',
            name='setor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ilhas', to='core.equipe', verbose_name='Setor / Equipe'),
        ),
    ]
