# Generated by Django 6.0.5 on 2026-07-24 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0002_alter_ilha_setor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operador',
            name='pa',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operador', to='operadores.pa', verbose_name='Posição de Atendimento (PA)'),
        ),
    ]
