# Generated by Django 6.0.5 on 2026-07-27 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0003_alter_operador_pa'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappaccount',
            name='account_type',
            field=models.CharField(choices=[('BUSINESS', 'WhatsApp Business'), ('STANDARD', 'WhatsApp Normal')], default='BUSINESS', help_text='Defina se a conta é WhatsApp Business ou Normal', max_length=20, verbose_name='Tipo de Conta'),
        ),
    ]
