# Generated by Django 6.0.5 on 2026-07-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0004_whatsappaccount_account_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='phone_number',
            field=models.CharField(blank=True, help_text='Número do WhatsApp', max_length=50, null=True, unique=True, verbose_name='Número / Identificador'),
        ),
    ]
