# Generated by Django 6.0.6 on 2026-07-28 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operadores', '0005_alter_whatsappaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='whatsappaccount',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Ativa'), ('RESTRICTED', 'Restringido'), ('SUSPENDED', 'Em Análise'), ('BANNED', 'Banido')], default='ACTIVE', max_length=20, verbose_name='Status da Conta'),
        ),
    ]
