# Generated by Django 6.0.5 on 2026-05-28 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Blacklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone_original', models.CharField(max_length=30)),
                ('telefone_normalizado', models.CharField(db_index=True, max_length=20)),
                ('cpf', models.CharField(blank=True, db_index=True, max_length=20, null=True)),
                ('qualificacao_origem', models.CharField(max_length=100)),
                ('campanha_id', models.CharField(blank=True, max_length=100, null=True)),
                ('campanha_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('call_id', models.CharField(blank=True, max_length=100, null=True)),
                ('data_ligacao', models.DateTimeField(blank=True, null=True)),
                ('tipo_bloqueio', models.CharField(max_length=20)),
                ('bloqueado_em', models.DateTimeField()),
                ('bloqueado_ate', models.DateTimeField(blank=True, null=True)),
                ('origem', models.CharField(choices=[('api', 'API'), ('csv', 'CSV'), ('manual', 'Manual')], default='api', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('payload_original', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ConfiguracaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('base_url', models.URLField(max_length=255)),
                ('api_token', models.CharField(max_length=255)),
                ('campaign_ids', models.CharField(help_text='IDs separados por vírgula', max_length=255)),
                ('per_page', models.IntegerField(default=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='LigacaoImportada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('call_id', models.CharField(max_length=100, unique=True)),
                ('telefone_original', models.CharField(max_length=30)),
                ('telefone_normalizado', models.CharField(max_length=20)),
                ('campanha_id', models.CharField(max_length=100)),
                ('campanha_nome', models.CharField(max_length=150)),
                ('agente_nome', models.CharField(blank=True, max_length=150, null=True)),
                ('status', models.CharField(max_length=100)),
                ('qualificacao', models.CharField(max_length=100)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_ligacao', models.DateTimeField()),
                ('payload_original', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='RegraReciclagem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qualificacao', models.CharField(max_length=100)),
                ('acao', models.CharField(choices=[('bloquear', 'Bloquear'), ('ignorar', 'Ignorar'), ('monitorar', 'Monitorar')], max_length=20)),
                ('tipo_bloqueio', models.CharField(blank=True, choices=[('temporario', 'Temporário'), ('permanente', 'Permanente')], max_length=20, null=True)),
                ('dias_bloqueio', models.IntegerField(default=0, help_text='Se temporário, quantos dias bloquear?')),
                ('aplicar_por_telefone', models.BooleanField(default=True)),
                ('aplicar_por_cpf', models.BooleanField(default=False)),
                ('campanha_id', models.CharField(blank=True, help_text='Deixe em branco para todas', max_length=100, null=True)),
                ('prioridade', models.IntegerField(default=1, help_text='Maior número = maior prioridade')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ImportacaoAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_fim', models.DateTimeField(blank=True, null=True)),
                ('periodo_inicial', models.DateTimeField()),
                ('periodo_final', models.DateTimeField()),
                ('campanhas', models.CharField(max_length=255)),
                ('total_ligacoes', models.IntegerField(default=0)),
                ('total_com_qualificacao', models.IntegerField(default=0)),
                ('total_bloqueios', models.IntegerField(default=0)),
                ('total_ignorados', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ProcessamentoBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('campanha_destino', models.CharField(max_length=150)),
                ('arquivo_original', models.FileField(upload_to='discador/originais/')),
                ('arquivo_reciclado', models.FileField(blank=True, null=True, upload_to='discador/reciclados/')),
                ('arquivo_bloqueados', models.FileField(blank=True, null=True, upload_to='discador/bloqueados/')),
                ('coluna_telefone', models.CharField(max_length=100)),
                ('coluna_cpf', models.CharField(blank=True, max_length=100, null=True)),
                ('total_linhas', models.IntegerField(default=0)),
                ('total_liberadas', models.IntegerField(default=0)),
                ('total_bloqueadas', models.IntegerField(default=0)),
                ('total_duplicadas', models.IntegerField(default=0)),
                ('total_erros', models.IntegerField(default=0)),
                ('status', models.CharField(max_length=50)),
                ('log', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('finalizado_em', models.DateTimeField(blank=True, null=True)),
                ('criado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
